server:
  port: 8003

spring:
  application:
    name: short-link-gateway
  profiles:
    # 聚合模式
    active: aggregation
    # 微服务模式
    # active: dev
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.1:8848