server:
  port: 8004

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      channel-topic:
        short-link-stats: 'short_link:stats-stream'
        short-link-stats-group: 'short_link:stats-stream:only-group'
  mvc:
    view:
      prefix: /templates/
      suffix: .html

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag  # 全局逻辑删除的实体字段名
      logic-delete-value: 1  # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0  # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

short-link:
  domain:
    default: nurl.ink:8004
  stats:
    locale:
      amap-key: 1d8cd341b8086ef4ade1d75d66ca5a58
  goto-domain:
    white-list:
      enable: false
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com